# Use root/example user/password credentials
version: '3.3'

services:
  website:
    build:
      context: website/
      dockerfile: Dockerfile
    ports:
      - 8080:80
#    volumes:
#      - ./website/src:/app/public

  db:
    build:
      context: database/
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ssd
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080