# Use root/example user/password credentials
version: '3.3'

services:
  website:
    build:
      context: website/
      dockerfile: Dockerfile
    ports:
      - 8080:80

  db:
    build:
      context: database/
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ssd
    volumes:
      - ./database/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080

volumes:
  mysql-data:
