FROM ndegardin/apache-wsgi

COPY ./src/ /usr/local/apache2/wsgi/

# Ik weet niet eens meer waarom ik dit heb toegevoegd want het veranderd letterlijk niks
COPY ./conf/httpd.conf /etc/apache2/httpd.conf